import type { DiagramRenderer, RenderedDiagram } from '../../application/index.js'

/**
 * Graphviz implementation of the DiagramRenderer port, via `@hpcc-js/wasm-graphviz`.
 *
 * Loaded on demand, never bundled: the wasm binary is ~1.5 MB and RENDERERS.md
 * §7 puts it in the on-demand column. A note with no DOT block never pays for
 * it, and the dynamic import is what makes that true.
 *
 * Two failures live here and they are not the same failure. A bad graph is the
 * author's to fix, so it earns Graphviz's own message. An engine that will not
 * start is the build's problem — the wasm needs `'wasm-unsafe-eval'` in the
 * shell's CSP (see `src-tauri/tauri.conf.json`), and without it WebKit refuses
 * to compile the module. That refusal is a paragraph of policy text that means
 * nothing to a reader and repeats on every DOT block in the document, so it is
 * answered with one plain sentence instead. WebKit still logs the refusal to
 * the console, where a developer is the one reading it.
 *
 * Either way the failure is returned as `{ ok: false }` rather than thrown —
 * the same contract Mermaid honours, so a broken graph shows an inline error
 * card with its source still editable rather than taking the document down.
 *
 * Output is SVG produced by Graphviz itself. It is not passed through
 * DOMPurify: unlike a pasted `<svg>`, this markup is generated by the engine
 * from the source text rather than supplied by the clipboard. Labels are
 * escaped by Graphviz on the way in.
 */

type GraphvizEngine = { layout(source: string, format: string, engine: string): string }

/** Seam for tests: the real loader pulls in 800 KB of wasm, which a unit test must not. */
export type GraphvizLoader = () => Promise<GraphvizEngine>

/** Shown when the wasm module will not compile — a build or platform fault, not a source fault. */
export const GRAPHVIZ_UNAVAILABLE =
  'Graphviz could not start in this build, so this graph was not drawn. The source is unchanged.'

const loadGraphviz: GraphvizLoader = () =>
  import('@hpcc-js/wasm-graphviz').then(
    (module) => module.Graphviz.load() as unknown as Promise<GraphvizEngine>,
  )

export class GraphvizRenderer implements DiagramRenderer {
  readonly languages = ['dot', 'graphviz'] as const

  readonly #load: GraphvizLoader

  /**
   * One wasm instance for the document, created the first time a graph renders.
   *
   * A rejected promise is cached deliberately. Why an engine failed to start —
   * a CSP that forbids wasm, a platform without it — does not change between
   * keystrokes, so retrying on every repaint would re-run the import once per
   * character typed and reach the same answer every time.
   */
  #engine: Promise<GraphvizEngine> | undefined

  constructor(load: GraphvizLoader = loadGraphviz) {
    this.#load = load
  }

  async render(language: string, source: string): Promise<RenderedDiagram> {
    if (!this.languages.includes(language as 'dot')) {
      return { ok: false, message: `GraphvizRenderer cannot render "${language}"` }
    }

    const trimmed = source.trim()
    if (trimmed === '') return { ok: false, message: 'Graph source is empty' }

    let graphviz: GraphvizEngine
    try {
      this.#engine ??= this.#load()
      graphviz = await this.#engine
    } catch {
      return { ok: false, message: GRAPHVIZ_UNAVAILABLE }
    }

    try {
      const svg = graphviz.layout(trimmed, 'svg', 'dot')
      if (typeof svg !== 'string' || svg.trim() === '') {
        return { ok: false, message: 'Graphviz produced no output for this source' }
      }
      return { ok: true, markup: svg }
    } catch (error) {
      return { ok: false, message: error instanceof Error ? error.message : String(error) }
    }
  }
}
