import type {
  ChartDataReader,
  DiagramRenderer,
  RenderedDiagram,
} from '../../application/index.js'
import { parseChartData, type ChartDataFormat } from './chart-data.js'
import { chartConfig } from './vega-lite-theme.js'

/**
 * Vega-Lite implementation of the DiagramRenderer port.
 *
 * Loaded on demand, never bundled: vega plus vega-lite is ~800 KB and
 * RENDERERS.md §7 puts charts in the on-demand column. A note with no chart
 * never pays for it, and the dynamic import is what makes that true.
 *
 * **The interpreter is not optional.** Vega compiles spec expressions with the
 * `Function` constructor, and the packaged CSP is `default-src 'self'` with no
 * `'unsafe-eval'` (src-tauri/tauri.conf.json). The default path fails there
 * with "Evaluating a string as JavaScript violates the following Content
 * Security Policy directive" — while passing in dev, vitest and Playwright,
 * none of which enforce the packaged policy. So the runtime is parsed with
 * `{ast: true}` and the view is given `vega-interpreter`, which evaluates the
 * AST instead of generating code. Measured both ways in spike/vega-csp before
 * this renderer was written.
 *
 * Output is SVG produced by Vega itself, from a spec the renderer parsed. It is
 * not passed through DOMPurify for the same reason Graphviz's output is not:
 * this markup is generated by the engine rather than supplied by the clipboard.
 */

/**
 * The same signal Mermaid reads, so both follow the reader's scheme together
 * (mermaid-renderer.ts). `DiagramNodeView` listens for changes to it and
 * repaints every rendered block, so charts inherit that for free.
 */
function prefersDark(): boolean {
  return (
    typeof window !== 'undefined' &&
    window.matchMedia?.('(prefers-color-scheme: dark)').matches === true
  )
}

const REMOTE = /^(https?|ftp):/i

const REMOTE_MESSAGE =
  'Remote data is not loaded. Put the values in the chart, or link a file next to your note.'

const NO_READER_MESSAGE =
  'This chart reads a data file, which is only available in the SimpleMark app.'

type VegaModules = {
  compile: typeof import('vega-lite').compile
  parse: typeof import('vega').parse
  View: typeof import('vega').View
  expressionInterpreter: typeof import('vega-interpreter').expressionInterpreter
}

/** One import for the document, resolved the first time a chart renders. */
let modulesPromise: Promise<VegaModules> | undefined

async function modules(): Promise<VegaModules> {
  modulesPromise ??= Promise.all([
    import('vega-lite'),
    import('vega'),
    import('vega-interpreter'),
  ]).then(([vegaLite, vega, interpreter]) => ({
    compile: vegaLite.compile,
    parse: vega.parse,
    View: vega.View,
    expressionInterpreter: interpreter.expressionInterpreter,
  }))
  return modulesPromise
}

/**
 * Replaces every `data: {url}` in the spec with the values from that file,
 * before Vega ever sees it.
 *
 * **Vega must not ingest the file itself.** Its ingestion path parses through
 * d3-dsv's `parse()`, which compiles a row constructor with `new Function` —
 * refused under the packaged CSP, whereupon Vega logs "Data ingestion failed"
 * and renders axes with no marks. `vega-interpreter` does not cover this; it
 * replaces expression codegen in the dataflow, and ingestion is a separate
 * path. So the file is read and parsed here (`chart-data.ts`, no codegen) and
 * handed over as plain values.
 *
 * Recursive because a url can sit under `layer`, `concat`, `facet`, or a
 * `lookup` transform's `from.data`, not only at the top.
 */
async function inlineDataUrls(
  node: unknown,
  resolve: (href: string, format?: ChartDataFormat) => Promise<unknown[]>,
): Promise<void> {
  if (Array.isArray(node)) {
    for (const item of node) await inlineDataUrls(item, resolve)
    return
  }
  if (typeof node !== 'object' || node === null) return

  const record = node as Record<string, unknown>
  const data = record['data']
  if (typeof data === 'object' && data !== null && !Array.isArray(data)) {
    const dataRecord = data as Record<string, unknown>
    const url = dataRecord['url']
    if (typeof url === 'string') {
      const values = await resolve(url, dataRecord['format'] as ChartDataFormat | undefined)
      const { url: _url, format: _format, ...rest } = dataRecord
      record['data'] = { ...rest, values }
    }
  }

  for (const value of Object.values(record)) await inlineDataUrls(value, resolve)
}

export class VegaLiteRenderer implements DiagramRenderer {
  readonly languages = ['vega-lite'] as const

  constructor(private readonly dataReader?: ChartDataReader) {}

  /** Reads and parses one data file, or explains why it cannot. */
  async #resolveData(href: string, format?: ChartDataFormat): Promise<unknown[]> {
    if (REMOTE.test(href)) throw new Error(REMOTE_MESSAGE)
    if (this.dataReader === undefined) throw new Error(NO_READER_MESSAGE)
    const text = await this.dataReader.read(href)
    return parseChartData(text, href, format)
  }

  /**
   * Vega's loader, narrowed to the one thing a chart is allowed to read.
   *
   * Vega swallows load failures into its own logger and renders an empty chart
   * rather than rejecting, so the first refusal is captured here and reported
   * by `render`. Without that, a chart pointing at a missing file would draw
   * empty axes and look like a chart with no data in it — a silent wrong
   * answer, which DESIGN.md §4.4 forbids.
   */
  #loader(failure: { message?: string }) {
    const refuse = (uri: string): string | undefined => {
      if (REMOTE.test(uri)) return REMOTE_MESSAGE
      if (this.dataReader === undefined) return NO_READER_MESSAGE
      return undefined
    }
    const guard = (uri: string): void => {
      const message = refuse(uri)
      if (message === undefined) return
      failure.message ??= message
      throw new Error(message)
    }
    return {
      sanitize: async (uri: string) => {
        guard(uri)
        return { href: uri }
      },
      load: async (uri: string) => {
        guard(uri)
        try {
          return await this.dataReader!.read(uri)
        } catch (error) {
          failure.message ??= error instanceof Error ? error.message : String(error)
          throw error
        }
      },
      http: async () => {
        failure.message ??= REMOTE_MESSAGE
        throw new Error(REMOTE_MESSAGE)
      },
      file: async () => {
        failure.message ??= NO_READER_MESSAGE
        throw new Error(NO_READER_MESSAGE)
      },
    }
  }

  async render(language: string, source: string): Promise<RenderedDiagram> {
    if (!this.languages.includes(language as 'vega-lite')) {
      return { ok: false, message: `VegaLiteRenderer cannot render "${language}"` }
    }

    const trimmed = source.trim()
    if (trimmed === '') return { ok: false, message: 'Chart source is empty' }

    let spec: unknown
    try {
      spec = JSON.parse(trimmed)
    } catch (error) {
      return { ok: false, message: error instanceof Error ? error.message : String(error) }
    }

    try {
      // Before anything else: the file reads, so a failure here is reported as
      // itself rather than surfacing later as a chart with nothing in it.
      await inlineDataUrls(spec, (href, format) => this.#resolveData(href, format))

      const { compile, parse, View, expressionInterpreter } = await modules()
      // The house config goes in as the compile-time config, which is the
      // layer the spec's own settings override rather than replace.
      type CompileOptions = NonNullable<Parameters<typeof compile>[1]>
      const compiled = compile(spec as Parameters<typeof compile>[0], {
        config: chartConfig(prefersDark()) as unknown as NonNullable<CompileOptions['config']>,
      }).spec
      const runtime = parse(compiled, {}, { ast: true })
      const failure: { message?: string } = {}
      type ViewOptions = NonNullable<ConstructorParameters<typeof View>[1]>
      const view = new View(runtime, {
        renderer: 'none',
        expr: expressionInterpreter,
        // A refused load is reported through `failure`, so Vega's own console
        // logging would only duplicate it — and would do so in test output.
        logLevel: 0,
        loader: this.#loader(failure) as unknown as NonNullable<ViewOptions['loader']>,
      })
      const svg = await view.toSVG()
      view.finalize()
      if (failure.message !== undefined) return { ok: false, message: failure.message }
      if (typeof svg !== 'string' || svg.trim() === '') {
        return { ok: false, message: 'Vega-Lite produced no output for this chart' }
      }
      return { ok: true, markup: svg }
    } catch (error) {
      return { ok: false, message: error instanceof Error ? error.message : String(error) }
    }
  }
}
